name: Recent Activity Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  activity-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Recent Activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TheM1ddleM1n
          filename: metrics.plugin.activity.svg
          template: classic
          base: header, activity, metadata
          plugin_recent_activity: yes
          plugin_recent_activity_limit: 5
          plugin_recent_activity_days: 7
          plugin_recent_activity_show: commits, issues, pull_requests
