name: Recent Activity Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  activity-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Recent Activity
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: TheM1ddleM1n
          filename: metrics.plugin.activity.svg
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 7
          plugin_activity_filter: all
