name: Ghost Notification Cleaner

on:
  schedule:
    - cron: '*/30 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean ghost notifications
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/notifications \
            | jq '.[] | select(
                (.repository.full_name | test("ping-plasma")) or
                (.subject.title | test("crypto|#174831"))
              ) | .id' \
            | while read id; do
                curl -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
                  https://api.github.com/notifications/threads/$id \
                  -d '{"read":true}'
              done
