name: Cleanup Notifications

on:
  workflow_dispatch:
    inputs:
      since:
        description: 'ISO 8601 timestamp (e.g. 2025-09-25T00:00:00Z)'
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run cleanup script
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node cleanupNotifications.js "${{ github.event.inputs.since }}"
