name: Mark All Notifications as Read (stops ghost messages showing a blue notification!)

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:

jobs:
  mark-read:
    runs-on: ubuntu-latest
    steps:
      - name: Mark all notifications as read
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          curl -X PUT -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/notifications \
            -d '{"last_read_at":"'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'"}'
