name: Update Status Based on Commits

on:
  push:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get latest commit timestamp and update README
        run: |
          latest_commit=$(git log -1 --format=%ct)
          now=$(date +%s)
          diff=$(( now - latest_commit ))

          if [ "$diff" -lt 3600 ]; then
            status="🟢 Online"
            message="TheM1ddleM1n is in full flow. Commits are flying, vibes are high."
          elif [ "$diff" -lt 259200 ]; then
            status="🧘‍♂️ Idle"
            message="Brewing ideas in the background. TheM1ddleM1n is in low-power creative mode."
          else
            status="⚪ Offline"
            message="Recharging in the shadows. TheM1ddleM1n will return with fire."
          fi

          sed -i '/<!--STATUS-->.*<!--END_STATUS-->/c\### Status: <!--STATUS-->'"$status"'<!--END_STATUS-->' README.md
          sed -i '/<!--STATUS_MESSAGE-->.*<!--END_STATUS_MESSAGE-->/c\<!--STATUS_MESSAGE-->'"$message"'<!--END_STATUS_MESSAGE-->' README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto-update status to ${{ steps.update-status.outputs.status }}"
