name: Update Followers

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Configure Git identity
        run: |
          git config --global user.name "ModuleMaster64 (via GitHub Actions)"
          git config --global user.email "192749026+ModuleMaster64@users.noreply.github.com"

      - name: Run update script
        run: python update_followers.py

      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/ModuleMaster64/ModuleMaster64.git
          git add README.md
          git commit -m "Auto-update followers" || echo "No changes to commit"
          git push
