name: Update Recent Followers

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Manual trigger option

jobs:
  update-followers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch recent followers and update README
        env:
          GH_USERNAME: ModuleMaster64
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python update_followers.py

      - name: Commit changes if needed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git diff --cached --quiet || git commit -m "🤖 Updated recent followers"
          git push origin HEAD:main
